#!/sbin/busybox sh

if [ -f /system/xbin/su ]; then
	echo "You have full working ROOT Installed!";
elif [ -f /system/bin/su ]; then
	echo "You have full working ROOT Installed!";
else
	echo "You don't have ROOT installed!";
fi;

